### ISSUE TITLE
Can give more info of this mod?

### ISSUE THREAD

**Issue by BigIcebergWei** [JustAPotota/Break-Free#1]
Can give more info of this mod? I don't know how to use it. Thanks~

**Comment by JustAPotota** [comment]
There's not much to it. The mod doesn't add anything, just changes an existing mechanic:

## Vanilla
![vanilla](https://user-images.githubusercontent.com/43710172/131745248-00ac14b3-b9de-4558-9c5f-c11ae4fdb0a3.gif)

## Break Free
![modded](https://user-images.githubusercontent.com/43710172/131745259-37260cca-8a13-475a-a3ab-42b298e48d81.gif)

If you have a question about something specific, I'd be happy to answer it.
